name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Game Build
          path: target/*.jar
      - name: Archive level data
        uses: actions/upload-artifact@v2
        with:
          name: Game Build
          path: actions/levels/**
      - name: Archive assets
        uses: actions/upload-artifact@v2
        with:
          name: Game Build
          path: actions/assets/**
